version: "3"

services: 
  main:
      build: .
      ports:
        - "8000:80"
        - "8001:443"
      environment:
        - ASPNETCORE_HTTPS_PORT=8001
        - ASPNETCORE_Kestrel__Certificates__Default__Password=0703wvw1104
        - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
        - ASPNETCORE_URLS=https://+;http://+
      volumes:
        - ${HOME}/.aspnet/https:/https/
      depends_on: 
        - db
  db: 
    image: "mcr.microsoft.com/mssql/server"
    ports: 
      - "1433:1433"
    environment: 
      SA_PASSWORD: "Admin123!"
      ACCEPT_EULA: "Y"